### ISSUE TITLE
Can't add omnipay-payu to composer laravel 5.1

### ISSUE THREAD

**Issue by luchiniii** [efesaid/omnipay-payu#2]
Hello

I can't figure out how to integrate this module with omnipay and laravel 5.1

When I set this on the composer.json and execute composer update I get this.

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package omnipay/payu could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

thanks for your help.

**Comment by JakeFalcor** [comment]
Hi @luchiniii,

Remember that this package has no *stable* version out. Composer is correctly complaining about stability level.  
If it is complaining when executing `composer require omnipay/payu`, then you might consider adding it manually in composer.json (`"omnipay/payu": "dev-master"`). If that doesn't help, then probably you have `minimum-stability` set.

Cheers.

**Comment by janeczeq25** [comment]
@JakeFalcor Unfortunately, that did not work, please help!

**Comment by efesaid** [comment]
`composer show omnipay/payu` shows that there are two versions of package.
`versions : dev-master, 2.0.x-dev`

@janeczeq25 please update composer to newest version and clear composer cache ` composer clearcache` and then try agin `composer require omnipay/payu`

**Comment by janeczeq25** [comment]
Thank you very much for your answer!
The following entry in composer.json helped!
"minimum-stability": "dev",

**Comment by efesaid** [comment]
always use latest version of composer and consider minimum-stability option.

**Comment by juavidn** [comment]
@Steveb-p thank you setting manually "omnipay/payu": "dev-master" worked for me ! :+1:
